// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using desafio_.Net.Contexts;

namespace desafio.Net.Migrations
{
    [DbContext(typeof(UsuarioDbContext))]
    [Migration("20190128163511_First Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("desafio_.Net.Models.Phone", b =>
                {
                    b.Property<int>("number")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("UsuarioID");

                    b.Property<int>("area_code");

                    b.Property<int>("coutry_code");

                    b.HasKey("number");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("desafio_.Net.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("password");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("desafio_.Net.Models.Phone", b =>
                {
                    b.HasOne("desafio_.Net.Models.Usuario", "Usuario")
                        .WithMany("Phones")
                        .HasForeignKey("UsuarioID");
                });
#pragma warning restore 612, 618
        }
    }
}
